### ISSUE TITLE
DeleteDocumentAsync throws and exception with v 1.1.4 (stable with 1.0.3)

### ISSUE THREAD

**Issue by piffy76** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#100]
Hi,

If I use 1.0.3, DeleteDocumentAsync works well. If I use 1.1.4, it throws an exception as below.

System.InvalidOperationException: 'There is already an open DataReader associated with this Connection which must be closed first.'

I did not test the other versions between the two.

Thank you.

**Comment by marcominerva** [comment]
I have a similar issue with `DeleteDocumentAsync`, but in my case it is a timeout exception, so I have opened another issue here: https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer/issues/101
