### ISSUE TITLE
SQL Server Connection successful but when I ask always receive 'INFO NOT FOUND' message

### ISSUE THREAD

**Issue by patorbor** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#107]
Hi @kbeaugrand ,

The connection to SQL Server is successful, but when I ask always receive "INFO NOT FOUND" message.

What I'm missing.

For example, in the database I have a table called 'Operarios'. when I ask "How much operarios are?" "INFO NOT FOUND" message is received

I test with this code (OpenAI api key and SQL sa password are hidden for security):

            memory = new KernelMemoryBuilder()
                .WithOpenAIDefaults("<OpenAI api key>")
                .WithSqlServerMemoryDb("Server=(local)\\DISCOM;Database=Visdeltex;User Id=sa;Password=<SAPassword>;TrustServerCertificate=True;")
                .Build<MemoryServerless>();

**Comment by kbeaugrand** [comment]
Hello, 

These connectors are not NL 2 SQL features, they are supposed to be used by Retrieval Augmented Generation.
You will therefore need to vectorize and index your data to use SemanticKernel or KernelMemory.

Take a look at KernelMemory to see what it's all about.
