### ISSUE TITLE
Cannot add WithMemoryStorage to semantickernel

### ISSUE THREAD

**Issue by Christofferjensen** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#117]
I'm trying to use these examples in a c# project

I cannot get it to work?

var kernel = new KernelBuilder()
    .Configure(
        config =>
        {
            config.AddAzureOpenAITextCompletion(...);
            config.AddAzureOpenAIEmbeddingGeneration(...);
        })
    .WithMemoryStorage(new VolatileMemoryStore())
    .Build();

OR

using SemanticKernel.Connectors.Memory.SqlServer;

var kernel = Kernel.Builder
                .WithMemoryStorage(await SqlServerMemoryStore.ConnectAsync(connectionString: "Server=.;Database=SK;Trusted_Connection=True;"))
                .Build();

I added the nuget package "SemanticKernel.Connectors.Memory.SqlServer"

None of the examples are working.
the "WithMemoryStorage" method does not exist in any of the packages i've tried.

Any help would be much appreciated
Thank you

**Comment by kbeaugrand** [comment]
@Christofferjensen , did you try this: 
```
using SemanticKernel.Connectors.Memory.SqlServer;
...
var kernel = Kernel.Builder
            ...
                .WithMemoryStorage(await SqlServerMemoryStore.ConnectAsync(connectionString: "Server=.;Database=SK;Trusted_Connection=True;"))
            ...
                .Build();
```

**Comment by Christofferjensen** [comment]
Hi 
Yes, i tried that snippet.  What's going on with the 3 dots? "..."

![image](https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer/assets/3885971/4bc19d4a-8751-4e9d-8b10-19565b12df82)

After removing the 3 dots "...", 

![image](https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer/assets/3885971/333d6a36-cde8-42d1-b7c9-1ee5cf494f54)

I must be missing something here?
Thank you

**Comment by kbeaugrand** [comment]
The three dots represents ommitted lines for brievety.
If you don't have further configuration to add this would suffice.

**Comment by Christofferjensen** [comment]
I tried removing the 3 dots. the snippet still does not work. 
Like i said, in my 2 previous posts. See image:

![image](https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer/assets/3885971/1f8924ce-b942-487b-9c87-d7d97ab62e01)

Any help would be much appreciated
Thank you

**Comment by kbeaugrand** [comment]
Hooo, this is simply because of the version of the Semantic Kernel you are using. Signatures of KernelBuilder has changed over the time (and my sample is not accurate).

Latest version of SK should give something like this: 
``` 
var kernel = Kernel.CreateBuilder()
                .WithMemoryStorage(await SqlServerMemoryStore.ConnectAsync(connectionString: "Server=.;Database=SK;Trusted_Connection=True;"))
                .Build();
```

**Comment by Christofferjensen** [comment]
Hi again. Ok, now we are getting closer.
I also tried that. The "WithMemoryStorage" method is not available. I have installed all packages related to SemanticKernel.
Also the nuget package "SemanticKernel.Connectors.Memory.SqlServer". The "WithMemoryStorage" method is not available.

var kernel = Kernel.CreateBuilder()
                .WithMemoryStorage(await SqlServerMemoryStore.ConnectAsync(connectionString: "Server=.;Database=SK;Trusted_Connection=True;"))
                .Build();

![image](https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer/assets/3885971/8245e0ce-d64c-4ee6-a400-c0e151dd1b56)

Here is a picture of the packages i have installed.

![image](https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer/assets/3885971/ce9d0d6d-9a65-4e78-97c7-31c83d73fcdd)

Omg. What am i missing here?
Hope you can help
Thank you

**Comment by kbeaugrand** [comment]
Yes, 

This is because SK memory is now obsolete. 
You should use TextMemoryPlugin to work directly with this connector.

Here is the corresponding code: 
```
#pragma warning disable SKEXP0052 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
#pragma warning disable SKEXP0001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
        
        var kernel = Kernel.CreateBuilder()
            .Build();

        var sqlMemoryStore = await SqlServerMemoryStore.ConnectAsync(connectionString: "Server=.;Database=SK;Trusted_Connection=True;");
        var semanticTextMemory = new SemanticTextMemory(sqlMemoryStore, kernel.GetRequiredService<ITextEmbeddingGenerationService>());
        kernel.ImportPluginFromObject(new TextMemoryPlugin(semanticTextMemory));

#pragma warning restore SKEXP0001 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
#pragma warning restore SKEXP0052 // Type is for evaluation purposes only and is subject to change or removal in future updates. Suppress this diagnostic to proceed.
``` 

However, as you can see, this is experimental and, I encourage you to use KernelMemory connector instead which is a more appropriate way to benefit from Semantic memories, there is also a specific plugin to ask and retrieve embeddings with SK.

**Comment by Christofferjensen** [comment]
Alright. I finally came full circle. 😁
I started writing the plugin using the kernelmemory connector. The example is in the GitHub semanticketnel repository. The example had no code for accessing sql memory data. Only using a webclient.
So i found your snippet of code to acces kernelmemory from plugins. 
I will try this code you provided. Thank you so much for your help.

**Comment by kbeaugrand** [comment]
you're welcome
