### ISSUE TITLE
not getting relevant answers from asks 

### ISSUE THREAD

**Issue by giannik** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#15]
From my initial tests on some embeddings Im not getting consistent results.
.I can see the **GetNearestMatchesAsync** method called but the results are not related to the questions i ask .

**Comment by kbeaugrand** [comment]
Hi,

Can you share a sample code ?

**Comment by giannik** [comment]
sure .

For example a have stored in the database the following   memory record for an index named blogposts: 


```
Elon Reeve Musk is a business magnate and investor. 
Musk is the founder, chairman, CEO and chief technology officer of SpaceX; angel investor, CEO, product architect and former chairman of Tesla, Inc.
founder of the Boring Company; co-founder of Neuralink and OpenAI; and president of the Musk Foundation. 
```


next i run a search where theask ="who is elon musk"

It returns all records even ones without elon musk.

Next I run theask ="who is steve jobs"

it returns again all records even though i have nothing on steve jobs

```
  var kernel = Kernel.Builder
                .WithLogger (_logger )
                .WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", decryptedOpenAiKey )
                .WithMemoryStorage(await SqlServerMemoryStore.ConnectAsync(_dbConnectionString))
                .Build();
             var memoryCollectionName = index;  
             try
            {
                var memoriesResponse =   kernel.Memory.SearchAsync(memoryCollectionName, theAsk, limit: limit, minRelevanceScore: relevanceScore);
                await foreach (var memory in memoriesResponse)
                {
                   // Console.WriteLine($"Result {++counter}:\n  >> {memory.Metadata.Id}\n  Text: {memory.Metadata.Text}  Relevance: {memory.Relevance}\n");
                 }

            }

```

**Comment by kbeaugrand** [comment]
Ok thank you for this sample.

I'll take a look into it in the next week.
I will give you in touch.

**Comment by kbeaugrand** [comment]
@giannik, 

After a try on Azure SQL Server, I get a match for the data you provided to me. 
The relevance between your data and the ask is about 0.88 which seems to be good.

I also tested the same program with an Azure Cognitive Search (vector search). The relevance is about 0.89 (which is different, and I don't know why, be not so far).

Can you try to adjust your settings (min relevance), or see if other entries are simply more relevant to your question? 

Regards,
