### ISSUE TITLE
Any plans for Kernel Memory connector?

### ISSUE THREAD

**Issue by Matt-Scheetz** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#66]
Semantic Kernel has been moving memory out to the Kernel Memory (KM) project.  Any plans to update this for integration with KM?

https://github.com/microsoft/kernel-memory

**Comment by kbeaugrand** [comment]
I will do this week-end. Stay tuned

**Comment by kbeaugrand** [comment]
Please find the package at : [https://www.nuget.org/packages/KernelMemory.MemoryStorage.SqlServer/](https://www.nuget.org/packages/KernelMemory.MemoryStorage.SqlServer/).

Don't hesitate to create issues in this GitHub repository if you encounter any problem.

**Comment by kbeaugrand** [comment]
@Matt-Scheetz note that the kernel memory implementation is not compatible with the semantic kernel's one. So tables created with SK connectors have to be re-created with kernel memory
