### ISSUE TITLE
Add the ability to change table names

### ISSUE THREAD

**Issue by marcominerva** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#83]
Currently, table names are hard-coded. I think it would be useful to have the ability to specify custom names during configuration, like we can already do for the schema.

**Comment by kbeaugrand** [comment]
> Currently, table names are hard-coded. I think it would be useful to have the ability to specify custom names during configuration, like we can already do for the schema.

@marcominerva, I'll do that.
