### ISSUE TITLE
ImportTextAsync(..) blocking the UI, crashes website in the end

### ISSUE THREAD

**Issue by dmm-l-mediehus** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#95]
My code (a Blazor Web App project with a WorkerService: `builder.Services.AddHostedService<AIServiceWorker>();`) that imports documents (~60000 rows) into the Kernel Memory everyday:

```cs
public sealed class AIServiceWorker(IServiceScopeFactory serviceScopeFactory, IKernelMemory kernelMemory) : BackgroundService
{
	private DateTime nextRunTime = GetNextTargetTime();
	private bool initialTaskRun = false;

	protected override async Task ExecuteAsync(CancellationToken stoppingToken)
	{
		while (!stoppingToken.IsCancellationRequested)
		{
			DateTime currentTime = DateTime.Now;

			if (!initialTaskRun || currentTime >= nextRunTime)
			{
				await kernelMemory.DeleteIndexAsync("documents", stoppingToken).ConfigureAwait(false);

				await UpdateCMSAsync(stoppingToken).ConfigureAwait(false);

				initialTaskRun = true;

				nextRunTime = GetNextTargetTime().AddDays(1);
			}

			await Task.Delay(TimeSpan.FromHours(1), stoppingToken).ConfigureAwait(false);
		}
	}

	private static DateTime GetNextTargetTime()
	{
		DateTime targetTimeToday = DateTime.Today.AddHours(1);

		if (DateTime.Now > targetTimeToday)
		{
			targetTimeToday = targetTimeToday.AddDays(1);
		}

		return targetTimeToday;
	}

	private async Task UpdateCMSAsync(CancellationToken stoppingToken)
	{
		await using AsyncServiceScope scope = serviceScopeFactory.CreateAsyncScope();
		DocumentService documentService = scope.ServiceProvider.GetRequiredService<DocumentService>();
		ILogService logger = scope.ServiceProvider.GetRequiredService<ILogService>();

		DateTimeOffset startTime = DateTimeOffset.Now;
		await logger.LogInfoAsync($"Opdatering af dokumenter fra CMS er startet kl. {startTime:HH:mm:ss}", stoppingToken).ConfigureAwait(false);

		bool continueRetrieving = true;

		DocumentFilter documentFilter = new();
		documentFilter.Page = 1;
		documentFilter.PageSize = 1000;
		int finalCount = 0;

		while (continueRetrieving)
		{
			ResponseDTO<IReadOnlyCollection<DocumentDTO>> documentsResult = await documentService.GetDocumentListAsync(documentFilter, stoppingToken).ConfigureAwait(false);

			if (!documentsResult.IsSuccess)
			{
				await logger.LogErrorAsync("Failed to retrieve documents from CMS.", documentsResult.ExceptionMessage, documentsResult.StackTrace, null, stoppingToken);

				return;
			}

			if (documentsResult.Content!.Count == 0)
			{
				continueRetrieving = false;

				break;
			}

			finalCount += documentsResult.RecordCount;

			foreach (DocumentDTO document in documentsResult.Content)
			{
				StringBuilder documentSemanticText = new();
				documentSemanticText.AppendLine($"Titel: {document.HeadLine1 ?? document.HeadLine}\n");
				documentSemanticText.AppendLine($"Trumpet (kommer før titlen): {document.Trumpet1 ?? document.Trumpet}\n");
				documentSemanticText.AppendLine($"Introduktion: {document.Introduction}\n");
				documentSemanticText.AppendLine($"Artiklens link: {document.Link}\n");
				documentSemanticText.AppendLine($"Oprettelsesdato: {document.ShowOnWebFrom?.ToLongDateString()}");

				await kernelMemory.ImportTextAsync(
					text: documentSemanticText.ToString(),
					documentId: document.DocumentID.ToString(),
					index: "documents",
					cancellationToken: stoppingToken).ConfigureAwait(false);

				// Commented out, if commented in, it will be less prone to UI blocking, but will take longer to import
				//while (!await kernelMemory.IsDocumentReadyAsync(document.DocumentID.ToString(), "documents", stoppingToken).ConfigureAwait(false))
				//{
				//	await Task.Delay(1, stoppingToken).ConfigureAwait(false);
				//}
			}

			await logger.LogInfoAsync($"Imported {documentFilter.PageSize}/{documentsResult.RecordCount} documents successfully (page {documentFilter.Page}).", stoppingToken).ConfigureAwait(false);
			await Task.Delay(1000, stoppingToken).ConfigureAwait(false);

			documentFilter.Page++;
		}

		TimeSpan timeTook = DateTimeOffset.Now - startTime;
		await logger.LogInfoAsync($"Opdatering af dokumenter fra CMS er færdig kl. {DateTimeOffset.Now:HH:mm:ss}. Det tog {timeTook:c} at opdatere {finalCount} dokumenter.", stoppingToken).ConfigureAwait(false);
	}
}
```
This code works and uploads to database very fast (~500 documents in ~1 minute). But the more rows it uploads, it begins to block the UI and in the end it crashes the website (or database connection, not sure, but Blazor Server is inaccessible with default browser timeout error).

Check the code I commented out after ImportTextAsync, I do a while it isn't finished, Task.Delay 1 ms - it works okay without UI blocking, but it seems like a "hack" and isn't the best way to handle it. So that's why I created this issue. Also it is significantly slower (~500 documents in 9 minutes) when waiting for documents + 1ms delay...

First line is with the while checking each document + 1ms (doesn't block UI).
Second line without any waiting (blocks UI).
![image](https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer/assets/125255354/dc420881-9ea7-40b1-a3e9-e0e54c0d31a4)

**Comment by kbeaugrand** [comment]
@dmm-l-mediehus, Is your KM running in a server-less mode? 
If yes, I strongly encourage you to migrate to a service mode. 

KM works and scales at bast when running as a service, this won't break your app during the import process.

Otherwise, you can also limit the number of concurrent thread in your loop by adding a throttling and limiting the number of concurrent tasks. 

For example: 

```csharp
private async Task UpdateCMSAsync(CancellationToken stoppingToken)
{
    // ...

    // Create a SemaphoreSlim with a maximum of 10 concurrent tasks.
    SemaphoreSlim semaphore = new SemaphoreSlim(10);

    while (continueRetrieving)
    {
        // ...

        List<Task> tasks = new List<Task>();

        foreach (DocumentDTO document in documentsResult.Content)
        {
            // ...

            // Wait until there is an available slot.
            await semaphore.WaitAsync(stoppingToken).ConfigureAwait(false);

            Task task = kernelMemory.ImportTextAsync(
                text: documentSemanticText.ToString(),
                documentId: document.DocumentID.ToString(),
                index: "documents",
                cancellationToken: stoppingToken).ContinueWith(t =>
                {
                    // Release the slot when the task is done.
                    semaphore.Release();
                });

            tasks.Add(task);
        }

        // Wait for all tasks to complete.
        await Task.WhenAll(tasks).ConfigureAwait(false);

        // ...
    }

    // ...
}
```

This code creates a SemaphoreSlim with a maximum of 10 concurrent tasks. Before each ``ImportTextAsync`` call, it waits until there is an available slot. After each ``ImportTextAsync`` call, it releases the slot. This ensures that no more than 10 ``ImportTextAsync`` calls are running at the same time.

This approach should help to prevent UI blocking, as it limits the number of concurrent tasks. It should also be faster than the current approach of waiting for each document individually, as it allows multiple documents to be imported concurrently.

However, you may need to adjust the maximum number of concurrent tasks based on your specific requirements and the capabilities of your system. Too many concurrent tasks can still lead to UI blocking, while too few can slow down the import process.

**Comment by dmm-l-mediehus** [comment]
Running a Kernel Memory as a Service. Also that's a good idea, will try it - thanks! 

But if I am not alone with my issue here, I suggest changes to the nuget, since adjusting threads manually isn't the best option for consumers in my opinion.

**Comment by kbeaugrand** [comment]
If you're running KM as a service (meaning is a separate application), I guess this should should not occurs.

Regarding your comment, did you try with other kind of DBs, (like PostgreSQL)? I'm curious to see if I have a different behaviour behind the scene.

**Comment by dmm-l-mediehus** [comment]
I just separated the applications, so that it is like this:
- WebAPI Project (where the KM Service is at). 
- Blazor Server Project (that has a workerservice, calling the WebAPI KM Service with MemoryWebClient(...) instance instead)

Running it without waiting for document to finish ... it crashes my WebAPI Project website, it gets reestablished, then it starts over working for a minute, then it crashes.. repeatedly.

I haven't tried other ones than Azure AI Search and your SQL Server. Azure AI Search works as expected (changing one line in KM DI setup, to WithAzureAI()...

I will try with the Semaphore now.

**Comment by kbeaugrand** [comment]
@dmm-l-mediehus, are you able to provide me a sample program that demonstrate this issue please?

**Comment by kbeaugrand** [comment]
Honestly, this is really a strange behavior that I'm not able to explain now. 

I'm about to close this issue now since you're the only one reporting it. But don't hesitate to reach me out in case you have more questions.
